/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ProjectsPage {
    }
}
declare global {
    interface HTMLProjectsPageElement extends Components.ProjectsPage, HTMLStencilElement {
    }
    var HTMLProjectsPageElement: {
        prototype: HTMLProjectsPageElement;
        new (): HTMLProjectsPageElement;
    };
    interface HTMLElementTagNameMap {
        "projects-page": HTMLProjectsPageElement;
    }
}
declare namespace LocalJSX {
    interface ProjectsPage {
    }
    interface IntrinsicElements {
        "projects-page": ProjectsPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "projects-page": LocalJSX.ProjectsPage & JSXBase.HTMLAttributes<HTMLProjectsPageElement>;
        }
    }
}
